export const allIcons = [
  { name: 'Full-time access', icon: 'bi-stopwatch' },
  { name: 'Access on mobile and tablet', icon: 'bi-phone' },
  { name: 'Certificate of Completion', icon: 'bi-award' },
  { name: 'Interactive quizzes', icon: 'bi-pencil-square' },
  { name: 'Practical assignments', icon: 'bi-file-earmark-check' },
  { name: 'Expert instructor support', icon: 'bi-person-circle' },
  { name: 'Lifetime access', icon: 'bi-infinity' },
  { name: 'Community access', icon: 'bi-people' },
  { name: 'Downloadable resources', icon: 'bi-file-earmark-text' },
  { name: 'Flexible learning schedule', icon: 'bi-calendar' },
  { name: 'Regular course updates', icon: 'bi-arrow-repeat' },
  { name: 'No time limit', icon: 'bi-clock' },
  { name: 'Multilingual support', icon: 'bi-globe' },
  { name: 'Progress tracking', icon: 'bi-bar-chart' },
  { name: 'Job-ready skills', icon: 'bi-briefcase' },
  { name: 'Discounts on future courses', icon: 'bi-tags' },
  { name: 'Peer-to-peer interaction', icon: 'bi-chat-square-dots' },
  { name: 'Access to industry experts', icon: 'bi-people-fill' },

  { name: 'Hands-on projects', icon: 'bi-joystick' },
  { name: 'Advanced learning tools', icon: 'bi-tools' },
  { name: 'Exclusive webinars and events', icon: 'bi-megaphone' },


  { name: 'Offline learning', icon: 'bi-cloud-download' },
  { name: 'Collaborative group projects', icon: 'bi-person-workspace' },
  { name: 'Real-time feedback', icon: 'bi-arrow-repeat' },
  { name: 'Career services', icon: 'bi-briefcase' },
  { name: 'Alumni network', icon: 'bi-person-lines-fill' },
  { name: 'Access to tools and software', icon: 'bi-laptop' },
  { name: 'No hidden fees', icon: 'bi-card-checklist' },
  { name: 'Personalized support', icon: 'bi-chat-left-dots' },
  { name: 'Virtual office hours', icon: 'bi-person-bounding-box' },
  { name: 'Football', icon: 'bi-emoji-sunglasses' },
  { name: 'Basketball', icon: 'bi-record-circle' },
  { name: 'Tennis', icon: 'bi-circle-half' },
  { name: 'Running', icon: 'bi-lightning' },
  { name: 'Cycling', icon: 'bi-bicycle' },
  { name: 'Swimming', icon: 'bi-droplet-half' },
  { name: 'Gym/Fitness', icon: 'bi-barbell' },
  { name: 'Medal/Award', icon: 'bi-award' },
  { name: 'Trophy', icon: 'bi-trophy' },
  { name: 'Stopwatch', icon: 'bi-stopwatch' },
  { name: 'Whistle/Referee', icon: 'bi-megaphone' },
  { name: 'Team Sports', icon: 'bi-people' },
  { name: 'Strategy/Planning', icon: 'bi-kanban' },
  { name: 'Match Schedule', icon: 'bi-calendar-event' },
  { name: 'Live Score', icon: 'bi-broadcast-pin' },
  { name: 'Fan/Supporters', icon: 'bi-chat-square-dots' },
  { name: 'Championship', icon: 'bi-stars' },
  { name: 'Training', icon: 'bi-mortarboard' },
  { name: 'Location (Stadium)', icon: 'bi-geo-alt' },
  { name: 'Ranking/Leaderboard', icon: 'bi-list-ol' },
  { name: 'Fitness Watch', icon: 'bi-watch' },
  { name: 'Energy', icon: 'bi-battery-full' },
  { name: 'Health Monitoring', icon: 'bi-heart-pulse' },
  { name: 'Weather (Outdoor Sports)', icon: 'bi-cloud-sun' },
  { name: 'Video Replay/Highlights', icon: 'bi-camera-video' },
  { name: 'Celebration', icon: 'bi-emoji-smile' },

  { name: 'Trophy', icon: 'bi-trophy' },
  { name: 'Medal', icon: 'bi-award' },
  { name: 'Star Performer', icon: 'bi-star-fill' },
  { name: 'Excellence', icon: 'bi-stars' },
  { name: 'Certificate', icon: 'bi-patch-check' },
  { name: 'Milestone Reached', icon: 'bi-flag' },
  { name: 'Top Rank', icon: 'bi-bar-chart-line' },
  { name: 'Leader', icon: 'bi-person-badge' },
  { name: 'Recognition', icon: 'bi-megaphone' },
  { name: 'Outstanding Contribution', icon: 'bi-hand-thumbs-up' },
  { name: 'Honor Roll', icon: 'bi-bookmark-star' },
  { name: 'Innovation Award', icon: 'bi-lightbulb' },
  { name: 'Team Success', icon: 'bi-people' },
  { name: 'Career Progression', icon: 'bi-graph-up-arrow' },
  { name: 'Years of Service', icon: 'bi-calendar-check' },
  { name: 'Community Impact', icon: 'bi-globe' },
  { name: 'Target Achieved', icon: 'bi-bullseye' },
  { name: 'Elite Status', icon: 'bi-gem' },
  { name: 'Mentorship Award', icon: 'bi-person-video2' },
  { name: 'Leadership Award', icon: 'bi-person-arms-up' },
  { name: 'Home', icon: 'bi-house-door' },
  { name: 'Search', icon: 'bi-search' },
  { name: 'User Profile', icon: 'bi-person' },
  { name: 'Edit', icon: 'bi-pencil-square' },
  { name: 'Delete', icon: 'bi-trash' },
  { name: 'Settings', icon: 'bi-gear' },
  { name: 'Notification', icon: 'bi-bell' },
  { name: 'Help/Support', icon: 'bi-question-circle' },
  { name: 'Download', icon: 'bi-download' },
  { name: 'Upload', icon: 'bi-upload' },
  { name: 'Login', icon: 'bi-box-arrow-in-right' },
  { name: 'Logout', icon: 'bi-box-arrow-right' },
  { name: 'Dashboard', icon: 'bi-speedometer2' },
  { name: 'Message/Chat', icon: 'bi-chat-dots' },
  { name: 'Calendar', icon: 'bi-calendar-event' },
  { name: 'Lock/Security', icon: 'bi-shield-lock' },
  { name: 'Camera', icon: 'bi-camera' },
  { name: 'Link', icon: 'bi-link-45deg' },
  { name: 'Document/File', icon: 'bi-file-earmark-text' },
  { name: 'Upload File', icon: 'bi-cloud-upload' },
  { name: 'Download File', icon: 'bi-cloud-download' },
  { name: 'Image/Media', icon: 'bi-image' },
  { name: 'Video/Media', icon: 'bi-camera-video' },
  { name: 'Like/Approve', icon: 'bi-hand-thumbs-up' },
  { name: 'Dislike/Reject', icon: 'bi-hand-thumbs-down' },
  { name: 'Eye/View', icon: 'bi-eye' },
  { name: 'Eye Slash/Hide', icon: 'bi-eye-slash' },
  { name: 'Clock/Time', icon: 'bi-clock' },
  { name: 'Mail/Email', icon: 'bi-envelope' },
  { name: 'Location/Map', icon: 'bi-geo-alt' },
  { name: 'Phone/Call', icon: 'bi-telephone' },
  { name: 'Cart/Shopping', icon: 'bi-cart' },
  { name: 'Money/Finance', icon: 'bi-currency-exchange' },
  { name: 'Save', icon: 'bi-bookmark-check' },
  { name: 'Warning/Alert', icon: 'bi-exclamation-triangle' },
  { name: 'Info', icon: 'bi-info-circle' },
  { name: 'Loading/Processing', icon: 'bi-arrow-repeat' },
  { name: 'Folder', icon: 'bi-folder' },
  { name: 'Tag/Label', icon: 'bi-tag' },
  { name: 'Plus/Add', icon: 'bi-plus' },
  { name: 'Minus/Remove', icon: 'bi-dash' },
  { name: 'Chevron Down', icon: 'bi-chevron-down' },
  { name: 'Chevron Up', icon: 'bi-chevron-up' },
  { name: 'Chevron Left', icon: 'bi-chevron-left' },
  { name: 'Chevron Right', icon: 'bi-chevron-right' }
];
